/**
 * Copyright (c) 2016-2017 by the respective copyright holders.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.zsmartsystems.zwave.commandclass.impl.loopback;

import static org.junit.Assert.assertEquals;

import java.util.Map;
import com.zsmartsystems.zwave.commandclass.impl.CommandClassSwitchBinaryV1;

/**
 * Class to implement loopback tests for command class <b>COMMAND_CLASS_SWITCH_BINARY</b> version <b>1</b>.
 * <p>
 * Note that this code is autogenerated. Manual changes may be overwritten.
 *
 * @author Chris Jackson - Initial contribution of Java code generator
 */
public class CommandClassSwitchBinaryV1LoopbackTest {
    /**
     * Performs an in/out test of the SWITCH_BINARY_SET command.
     * <p>
     * Test is designed to ensure that the command generates the same data
     * as the handler processes and is mainly a check of the code generator.
     *
     * @param switchValue {@link String}
     */
    public static void testSwitchBinarySetLoopback(String switchValue) {
        byte[] testPayload = CommandClassSwitchBinaryV1.getSwitchBinarySet(switchValue);

        Map<String, Object> response = CommandClassSwitchBinaryV1.handleSwitchBinarySet(testPayload);
        assertEquals(switchValue, (String) response.get("SWITCH_VALUE"));
    }

    /**
     * Performs an in/out test of the SWITCH_BINARY_REPORT command.
     * <p>
     * Test is designed to ensure that the command generates the same data
     * as the handler processes and is mainly a check of the code generator.
     *
     * @param value {@link String}
     */
    public static void testSwitchBinaryReportLoopback(String value) {
        byte[] testPayload = CommandClassSwitchBinaryV1.getSwitchBinaryReport(value);

        Map<String, Object> response = CommandClassSwitchBinaryV1.handleSwitchBinaryReport(testPayload);
        assertEquals(value, (String) response.get("VALUE"));
    }

}
