/**
 * Copyright (c) 2016-2017 by the respective copyright holders.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.zsmartsystems.zwave.commandclass.impl.loopback;

import static org.junit.Assert.assertEquals;

import java.util.Map;
import com.zsmartsystems.zwave.commandclass.impl.CommandClassSwitchAllV1;

/**
 * Class to implement loopback tests for command class <b>COMMAND_CLASS_SWITCH_ALL</b> version <b>1</b>.
 * <p>
 * Note that this code is autogenerated. Manual changes may be overwritten.
 *
 * @author Chris Jackson - Initial contribution of Java code generator
 */
public class CommandClassSwitchAllV1LoopbackTest {
    /**
     * Performs an in/out test of the SWITCH_ALL_SET command.
     * <p>
     * Test is designed to ensure that the command generates the same data
     * as the handler processes and is mainly a check of the code generator.
     *
     * @param mode {@link String}
     */
    public static void testSwitchAllSetLoopback(String mode) {
        byte[] testPayload = CommandClassSwitchAllV1.getSwitchAllSet(mode);

        Map<String, Object> response = CommandClassSwitchAllV1.handleSwitchAllSet(testPayload);
        assertEquals(mode, (String) response.get("MODE"));
    }

    /**
     * Performs an in/out test of the SWITCH_ALL_REPORT command.
     * <p>
     * Test is designed to ensure that the command generates the same data
     * as the handler processes and is mainly a check of the code generator.
     *
     * @param mode {@link String}
     */
    public static void testSwitchAllReportLoopback(String mode) {
        byte[] testPayload = CommandClassSwitchAllV1.getSwitchAllReport(mode);

        Map<String, Object> response = CommandClassSwitchAllV1.handleSwitchAllReport(testPayload);
        assertEquals(mode, (String) response.get("MODE"));
    }

}
