/**
 * Copyright (c) 2016-2017 by the respective copyright holders.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.zsmartsystems.zwave.commandclass.impl.loopback;

import static org.junit.Assert.assertEquals;

import java.util.Map;
import java.util.List;
import com.zsmartsystems.zwave.commandclass.impl.CommandClassHumidityControlModeV1;

/**
 * Class to implement loopback tests for command class <b>COMMAND_CLASS_HUMIDITY_CONTROL_MODE</b> version <b>1</b>.
 * <p>
 * Note that this code is autogenerated. Manual changes may be overwritten.
 *
 * @author Chris Jackson - Initial contribution of Java code generator
 */
public class CommandClassHumidityControlModeV1LoopbackTest {
    /**
     * Performs an in/out test of the HUMIDITY_CONTROL_MODE_SET command.
     * <p>
     * Test is designed to ensure that the command generates the same data
     * as the handler processes and is mainly a check of the code generator.
     *
     * @param mode {@link String}
     */
    public static void testHumidityControlModeSetLoopback(String mode) {
        byte[] testPayload = CommandClassHumidityControlModeV1.getHumidityControlModeSet(mode);

        Map<String, Object> response = CommandClassHumidityControlModeV1.handleHumidityControlModeSet(testPayload);
        assertEquals(mode, (String) response.get("MODE"));
    }

    /**
     * Performs an in/out test of the HUMIDITY_CONTROL_MODE_REPORT command.
     * <p>
     * Test is designed to ensure that the command generates the same data
     * as the handler processes and is mainly a check of the code generator.
     *
     * @param mode {@link String}
     */
    public static void testHumidityControlModeReportLoopback(String mode) {
        byte[] testPayload = CommandClassHumidityControlModeV1.getHumidityControlModeReport(mode);

        Map<String, Object> response = CommandClassHumidityControlModeV1.handleHumidityControlModeReport(testPayload);
        assertEquals(mode, (String) response.get("MODE"));
    }

    /**
     * Performs an in/out test of the HUMIDITY_CONTROL_MODE_SUPPORTED_REPORT command.
     * <p>
     * Test is designed to ensure that the command generates the same data
     * as the handler processes and is mainly a check of the code generator.
     *
     * @param bitMask {@link List<String>}
     */
    public static void testHumidityControlModeSupportedReportLoopback(List<String> bitMask) {
        byte[] testPayload = CommandClassHumidityControlModeV1.getHumidityControlModeSupportedReport(bitMask);

        Map<String, Object> response = CommandClassHumidityControlModeV1.handleHumidityControlModeSupportedReport(testPayload);
        assertEquals(bitMask, (List<String>) response.get("BIT_MASK"));
    }

}
