/**
 * Copyright (c) 2016-2017 by the respective copyright holders.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.zsmartsystems.zwave.commandclass.impl.loopback;

import static org.junit.Assert.assertEquals;

import java.util.Map;
import com.zsmartsystems.zwave.commandclass.impl.CommandClassThermostatSetbackV1;

/**
 * Class to implement loopback tests for command class <b>COMMAND_CLASS_THERMOSTAT_SETBACK</b> version <b>1</b>.
 * <p>
 * Note that this code is autogenerated. Manual changes may be overwritten.
 *
 * @author Chris Jackson - Initial contribution of Java code generator
 */
public class CommandClassThermostatSetbackV1LoopbackTest {
    /**
     * Performs an in/out test of the THERMOSTAT_SETBACK_SET command.
     * <p>
     * Test is designed to ensure that the command generates the same data
     * as the handler processes and is mainly a check of the code generator.
     *
     * @param setbackType {@link String}
     * @param setbackState {@link String}
     */
    public static void testThermostatSetbackSetLoopback(String setbackType, String setbackState) {
        byte[] testPayload = CommandClassThermostatSetbackV1.getThermostatSetbackSet(setbackType, setbackState);

        Map<String, Object> response = CommandClassThermostatSetbackV1.handleThermostatSetbackSet(testPayload);
        assertEquals(setbackType, (String) response.get("SETBACK_TYPE"));
        assertEquals(setbackState, (String) response.get("SETBACK_STATE"));
    }

    /**
     * Performs an in/out test of the THERMOSTAT_SETBACK_REPORT command.
     * <p>
     * Test is designed to ensure that the command generates the same data
     * as the handler processes and is mainly a check of the code generator.
     *
     * @param setbackType {@link String}
     * @param setbackState {@link String}
     */
    public static void testThermostatSetbackReportLoopback(String setbackType, String setbackState) {
        byte[] testPayload = CommandClassThermostatSetbackV1.getThermostatSetbackReport(setbackType, setbackState);

        Map<String, Object> response = CommandClassThermostatSetbackV1.handleThermostatSetbackReport(testPayload);
        assertEquals(setbackType, (String) response.get("SETBACK_TYPE"));
        assertEquals(setbackState, (String) response.get("SETBACK_STATE"));
    }

}
