/**
 * Copyright (c) 2014-2016 by the respective copyright holders.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.zsmartsystems.zwave.commandclass.impl;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Class to implement the Z-Wave command class <b>COMMAND_CLASS_MULTI_INSTANCE_ASSOCIATION</b> version <b>1</b>.<br>
 *
 * Command Class Multi Instance Association<br>
 *
 * This class provides static methods for processing received messages (message handler) and
 * methods to get a message to send on the Z-Wave network.<br>
 *
 * Note that this code is autogenerated. Manual changes may be overwritten.
 *
 * @author Chris Jackson - Initial contribution of Java code generator
 */
public class CommandClassMultiInstanceAssociationV1 {
    private static final Logger logger = LoggerFactory.getLogger(CommandClassMultiInstanceAssociationV1.class);

    /**
     * Integer command class key for COMMAND_CLASS_MULTI_INSTANCE_ASSOCIATION
     */
    public final static int COMMAND_CLASS_KEY = 0x8E;

    /**
     * Multi Instance Association Set Command Constant
     */
    public final static int MULTI_INSTANCE_ASSOCIATION_SET = 0x01;
    /**
     * Multi Instance Association Get Command Constant
     */
    public final static int MULTI_INSTANCE_ASSOCIATION_GET = 0x02;
    /**
     * Multi Instance Association Report Command Constant
     */
    public final static int MULTI_INSTANCE_ASSOCIATION_REPORT = 0x03;
    /**
     * Multi Instance Association Remove Command Constant
     */
    public final static int MULTI_INSTANCE_ASSOCIATION_REMOVE = 0x04;
    /**
     * Multi Instance Association Groupings Get Command Constant
     */
    public final static int MULTI_INSTANCE_ASSOCIATION_GROUPINGS_GET = 0x05;
    /**
     * Multi Instance Association Groupings Report Command Constant
     */
    public final static int MULTI_INSTANCE_ASSOCIATION_GROUPINGS_REPORT = 0x06;

    /**
     * Creates a new message with the MULTI_INSTANCE_ASSOCIATION_SET command.<br>
     *
     * Multi Instance Association Set<br>
     *
     *
     * @param groupingIdentifier {@link Integer}
     * @param nodeId {@link byte[]}
     * @return the {@link byte[]} array with the command to send
     */
    static public byte[] getMultiInstanceAssociationSet(Integer groupingIdentifier, byte[] nodeId) {
        logger.debug("Creating command message MULTI_INSTANCE_ASSOCIATION_SET version 1");

        ByteArrayOutputStream outputData = new ByteArrayOutputStream();
        outputData.write(COMMAND_CLASS_KEY);
        outputData.write(MULTI_INSTANCE_ASSOCIATION_SET);

        // Process 'Grouping identifier'
        outputData.write(groupingIdentifier);

        // Process 'Node ID'
        try {
            outputData.write(nodeId);
        } catch (IOException e) {
        }

        // Process 'Marker'
        outputData.write(0x00);

        // Process 'vg'

        return outputData.toByteArray();
    }

    /**
     * Processes a received frame with the MULTI_INSTANCE_ASSOCIATION_SET command<br>
     *
     * Multi Instance Association Set<br>
     *
     *
     * The output data {@link Map} has the following properties<br>
     *
     * <ul>
     * <li>GROUPING_IDENTIFIER {@link Integer}
     * <li>NODE_ID {@link byte[]}
     * </ul>
     *
     * @param payload the {@link byte[]} payload data to process
     * @return a {@link Map} of processed response data
     */
    public static Map<String, Object> handleMultiInstanceAssociationSet(byte[] payload) {
        // Create our response map
        Map<String, Object> response = new HashMap<String, Object>();

        // We're using variable length fields, so track the offset
        int msgOffset = 2;

        // Process 'Grouping identifier'
        response.put("GROUPING_IDENTIFIER", Integer.valueOf(payload[msgOffset]));
        msgOffset += 1;

        // Process 'Node ID'
        ByteArrayOutputStream valNodeId = new ByteArrayOutputStream();
        while (msgOffset < payload.length) {
            // Detect the marker
            if ((payload[msgOffset] & 0xFF) == 0x00) {
                break;
            }
            valNodeId.write(payload[msgOffset]);
            msgOffset++;
        }
        response.put("NODE_ID", valNodeId);

        // Process 'Marker'
        // Adjust position to account for the marker
        msgOffset += 1;

        // Process 'vg'

        // Create a list to hold the group vg
        List<Map<String, Object>> variantList = new ArrayList<Map<String, Object>>();

        int offset = msgOffset;
        while (offset < payload.length) {
            // Create a map to hold the members of this variant
            Map<String, Object> variant = new HashMap<String, Object>();

            // Process 'Multi Instance Node ID'
            variant.put("MULTI_INSTANCE_NODE_ID", Integer.valueOf(payload[msgOffset]));
            msgOffset += 1;

            // Process 'Instance'
            variant.put("INSTANCE", Integer.valueOf(payload[msgOffset]));
            msgOffset += 1;

            // Add to the list
            variantList.add(variant);

            // Add the length of this variant
            offset += (payload[offset + 0] & 0xFF) >> 0;
        }

        // Add the variant list to the response
        response.put("VG", variantList);
        msgOffset += 1;

        // Return the map of processed response data;
        return response;
    }

    /**
     * Creates a new message with the MULTI_INSTANCE_ASSOCIATION_GET command.<br>
     *
     * Multi Instance Association Get<br>
     *
     *
     * @param groupingIdentifier {@link Integer}
     * @return the {@link byte[]} array with the command to send
     */
    static public byte[] getMultiInstanceAssociationGet(Integer groupingIdentifier) {
        logger.debug("Creating command message MULTI_INSTANCE_ASSOCIATION_GET version 1");

        ByteArrayOutputStream outputData = new ByteArrayOutputStream();
        outputData.write(COMMAND_CLASS_KEY);
        outputData.write(MULTI_INSTANCE_ASSOCIATION_GET);

        // Process 'Grouping Identifier'
        outputData.write(groupingIdentifier);

        return outputData.toByteArray();
    }

    /**
     * Processes a received frame with the MULTI_INSTANCE_ASSOCIATION_GET command<br>
     *
     * Multi Instance Association Get<br>
     *
     *
     * The output data {@link Map} has the following properties<br>
     *
     * <ul>
     * <li>GROUPING_IDENTIFIER {@link Integer}
     * </ul>
     *
     * @param payload the {@link byte[]} payload data to process
     * @return a {@link Map} of processed response data
     */
    public static Map<String, Object> handleMultiInstanceAssociationGet(byte[] payload) {
        // Create our response map
        Map<String, Object> response = new HashMap<String, Object>();

        // Process 'Grouping Identifier'
        response.put("GROUPING_IDENTIFIER", Integer.valueOf(payload[2]));

        // Return the map of processed response data;
        return response;
    }

    /**
     * Creates a new message with the MULTI_INSTANCE_ASSOCIATION_REPORT command.<br>
     *
     * Multi Instance Association Report<br>
     *
     *
     * @param groupingIdentifier {@link Integer}
     * @param maxNodesSupported {@link Integer}
     * @param reportsToFollow {@link Integer}
     * @param nodeId {@link byte[]}
     * @return the {@link byte[]} array with the command to send
     */
    static public byte[] getMultiInstanceAssociationReport(Integer groupingIdentifier, Integer maxNodesSupported,
            Integer reportsToFollow, byte[] nodeId) {
        logger.debug("Creating command message MULTI_INSTANCE_ASSOCIATION_REPORT version 1");

        ByteArrayOutputStream outputData = new ByteArrayOutputStream();
        outputData.write(COMMAND_CLASS_KEY);
        outputData.write(MULTI_INSTANCE_ASSOCIATION_REPORT);

        // Process 'Grouping Identifier'
        outputData.write(groupingIdentifier);

        // Process 'Max Nodes Supported'
        outputData.write(maxNodesSupported);

        // Process 'Reports to Follow'
        outputData.write(reportsToFollow);

        // Process 'Node ID'
        try {
            outputData.write(nodeId);
        } catch (IOException e) {
        }

        // Process 'Marker'
        outputData.write(0x00);

        // Process 'vg'

        return outputData.toByteArray();
    }

    /**
     * Processes a received frame with the MULTI_INSTANCE_ASSOCIATION_REPORT command<br>
     *
     * Multi Instance Association Report<br>
     *
     *
     * The output data {@link Map} has the following properties<br>
     *
     * <ul>
     * <li>GROUPING_IDENTIFIER {@link Integer}
     * <li>MAX_NODES_SUPPORTED {@link Integer}
     * <li>REPORTS_TO_FOLLOW {@link Integer}
     * <li>NODE_ID {@link byte[]}
     * </ul>
     *
     * @param payload the {@link byte[]} payload data to process
     * @return a {@link Map} of processed response data
     */
    public static Map<String, Object> handleMultiInstanceAssociationReport(byte[] payload) {
        // Create our response map
        Map<String, Object> response = new HashMap<String, Object>();

        // We're using variable length fields, so track the offset
        int msgOffset = 2;

        // Process 'Grouping Identifier'
        response.put("GROUPING_IDENTIFIER", Integer.valueOf(payload[msgOffset]));
        msgOffset += 1;

        // Process 'Max Nodes Supported'
        response.put("MAX_NODES_SUPPORTED", Integer.valueOf(payload[msgOffset]));
        msgOffset += 1;

        // Process 'Reports to Follow'
        response.put("REPORTS_TO_FOLLOW", Integer.valueOf(payload[msgOffset]));
        msgOffset += 1;

        // Process 'Node ID'
        ByteArrayOutputStream valNodeId = new ByteArrayOutputStream();
        while (msgOffset < payload.length) {
            // Detect the marker
            if ((payload[msgOffset] & 0xFF) == 0x00) {
                break;
            }
            valNodeId.write(payload[msgOffset]);
            msgOffset++;
        }
        response.put("NODE_ID", valNodeId);

        // Process 'Marker'
        // Adjust position to account for the marker
        msgOffset += 1;

        // Process 'vg'

        // Create a list to hold the group vg
        List<Map<String, Object>> variantList = new ArrayList<Map<String, Object>>();

        int offset = msgOffset;
        while (offset < payload.length) {
            // Create a map to hold the members of this variant
            Map<String, Object> variant = new HashMap<String, Object>();

            // Process 'Multi Instance Node ID'
            variant.put("MULTI_INSTANCE_NODE_ID", Integer.valueOf(payload[msgOffset]));
            msgOffset += 1;

            // Process 'Instance'
            variant.put("INSTANCE", Integer.valueOf(payload[msgOffset]));
            msgOffset += 1;

            // Add to the list
            variantList.add(variant);

            // Add the length of this variant
            offset += (payload[offset + 0] & 0xFF) >> 0;
        }

        // Add the variant list to the response
        response.put("VG", variantList);
        msgOffset += 1;

        // Return the map of processed response data;
        return response;
    }

    /**
     * Creates a new message with the MULTI_INSTANCE_ASSOCIATION_REMOVE command.<br>
     *
     * Multi Instance Association Remove<br>
     *
     *
     * @param groupingIdentifier {@link Integer}
     * @param nodeId {@link byte[]}
     * @return the {@link byte[]} array with the command to send
     */
    static public byte[] getMultiInstanceAssociationRemove(Integer groupingIdentifier, byte[] nodeId) {
        logger.debug("Creating command message MULTI_INSTANCE_ASSOCIATION_REMOVE version 1");

        ByteArrayOutputStream outputData = new ByteArrayOutputStream();
        outputData.write(COMMAND_CLASS_KEY);
        outputData.write(MULTI_INSTANCE_ASSOCIATION_REMOVE);

        // Process 'Grouping identifier'
        outputData.write(groupingIdentifier);

        // Process 'Node ID'
        try {
            outputData.write(nodeId);
        } catch (IOException e) {
        }

        // Process 'Marker'
        outputData.write(0x00);

        // Process 'vg'

        return outputData.toByteArray();
    }

    /**
     * Processes a received frame with the MULTI_INSTANCE_ASSOCIATION_REMOVE command<br>
     *
     * Multi Instance Association Remove<br>
     *
     *
     * The output data {@link Map} has the following properties<br>
     *
     * <ul>
     * <li>GROUPING_IDENTIFIER {@link Integer}
     * <li>NODE_ID {@link byte[]}
     * </ul>
     *
     * @param payload the {@link byte[]} payload data to process
     * @return a {@link Map} of processed response data
     */
    public static Map<String, Object> handleMultiInstanceAssociationRemove(byte[] payload) {
        // Create our response map
        Map<String, Object> response = new HashMap<String, Object>();

        // We're using variable length fields, so track the offset
        int msgOffset = 2;

        // Process 'Grouping identifier'
        response.put("GROUPING_IDENTIFIER", Integer.valueOf(payload[msgOffset]));
        msgOffset += 1;

        // Process 'Node ID'
        ByteArrayOutputStream valNodeId = new ByteArrayOutputStream();
        while (msgOffset < payload.length) {
            // Detect the marker
            if ((payload[msgOffset] & 0xFF) == 0x00) {
                break;
            }
            valNodeId.write(payload[msgOffset]);
            msgOffset++;
        }
        response.put("NODE_ID", valNodeId);

        // Process 'Marker'
        // Adjust position to account for the marker
        msgOffset += 1;

        // Process 'vg'

        // Create a list to hold the group vg
        List<Map<String, Object>> variantList = new ArrayList<Map<String, Object>>();

        int offset = msgOffset;
        while (offset < payload.length) {
            // Create a map to hold the members of this variant
            Map<String, Object> variant = new HashMap<String, Object>();

            // Process 'Multi Instance Node ID'
            variant.put("MULTI_INSTANCE_NODE_ID", Integer.valueOf(payload[msgOffset]));
            msgOffset += 1;

            // Process 'Instance'
            variant.put("INSTANCE", Integer.valueOf(payload[msgOffset]));
            msgOffset += 1;

            // Add to the list
            variantList.add(variant);

            // Add the length of this variant
            offset += (payload[offset + 0] & 0xFF) >> 0;
        }

        // Add the variant list to the response
        response.put("VG", variantList);
        msgOffset += 1;

        // Return the map of processed response data;
        return response;
    }

    /**
     * Creates a new message with the MULTI_INSTANCE_ASSOCIATION_GROUPINGS_GET command.<br>
     *
     * Multi Instance Association Groupings Get<br>
     *
     *
     * @return the {@link byte[]} array with the command to send
     */
    static public byte[] getMultiInstanceAssociationGroupingsGet() {
        logger.debug("Creating command message MULTI_INSTANCE_ASSOCIATION_GROUPINGS_GET version 1");

        ByteArrayOutputStream outputData = new ByteArrayOutputStream();
        outputData.write(COMMAND_CLASS_KEY);
        outputData.write(MULTI_INSTANCE_ASSOCIATION_GROUPINGS_GET);

        return outputData.toByteArray();
    }

    /**
     * Processes a received frame with the MULTI_INSTANCE_ASSOCIATION_GROUPINGS_GET command<br>
     *
     * Multi Instance Association Groupings Get<br>
     *
     *
     * @param payload the {@link byte[]} payload data to process
     * @return a {@link Map} of processed response data
     */
    public static Map<String, Object> handleMultiInstanceAssociationGroupingsGet(byte[] payload) {
        // Create our response map
        Map<String, Object> response = new HashMap<String, Object>();

        // Return the map of processed response data;
        return response;
    }

    /**
     * Creates a new message with the MULTI_INSTANCE_ASSOCIATION_GROUPINGS_REPORT command.<br>
     *
     * Multi Instance Association Groupings Report<br>
     *
     *
     * @param supportedGroupings {@link Integer}
     * @return the {@link byte[]} array with the command to send
     */
    static public byte[] getMultiInstanceAssociationGroupingsReport(Integer supportedGroupings) {
        logger.debug("Creating command message MULTI_INSTANCE_ASSOCIATION_GROUPINGS_REPORT version 1");

        ByteArrayOutputStream outputData = new ByteArrayOutputStream();
        outputData.write(COMMAND_CLASS_KEY);
        outputData.write(MULTI_INSTANCE_ASSOCIATION_GROUPINGS_REPORT);

        // Process 'Supported Groupings'
        outputData.write(supportedGroupings);

        return outputData.toByteArray();
    }

    /**
     * Processes a received frame with the MULTI_INSTANCE_ASSOCIATION_GROUPINGS_REPORT command<br>
     *
     * Multi Instance Association Groupings Report<br>
     *
     *
     * The output data {@link Map} has the following properties<br>
     *
     * <ul>
     * <li>SUPPORTED_GROUPINGS {@link Integer}
     * </ul>
     *
     * @param payload the {@link byte[]} payload data to process
     * @return a {@link Map} of processed response data
     */
    public static Map<String, Object> handleMultiInstanceAssociationGroupingsReport(byte[] payload) {
        // Create our response map
        Map<String, Object> response = new HashMap<String, Object>();

        // Process 'Supported Groupings'
        response.put("SUPPORTED_GROUPINGS", Integer.valueOf(payload[2]));

        // Return the map of processed response data;
        return response;
    }

}
