/**
 * Copyright (c) 2016-2017 by the respective copyright holders.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.zsmartsystems.zwave.commandclass.impl;

import java.io.ByteArrayOutputStream;
import java.util.HashMap;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Class to implement the Z-Wave command class <b>COMMAND_CLASS_BASIC</b> version <b>1</b>.
 * <p>
 * Command Class Basic
 * <p>
 * This class provides static methods for processing received messages (message handler) and
 * methods to get a message to send on the Z-Wave network.
 * <p>
 * Command class key is 0x20.
 * <p>
 * Note that this code is autogenerated. Manual changes may be overwritten.
 *
 * @author Chris Jackson - Initial contribution of Java code generator
 */
public class CommandClassBasicV1 {
    private static final Logger logger = LoggerFactory.getLogger(CommandClassBasicV1.class);

    /**
     * Integer command class key for COMMAND_CLASS_BASIC
     */
    public final static int COMMAND_CLASS_KEY = 0x20;

    /**
     * Basic Set Command Constant
     */
    public final static int BASIC_SET = 0x01;
    /**
     * Basic Get Command Constant
     */
    public final static int BASIC_GET = 0x02;
    /**
     * Basic Report Command Constant
     */
    public final static int BASIC_REPORT = 0x03;


    /**
     * Creates a new message with the BASIC_SET command.
     * <p>
     * Basic Set
     *
     * @param value {@link Integer}
     * @return the {@link byte[]} array with the command to send
     */
    static public byte[] getBasicSet(Integer value) {
        logger.debug("Creating command message BASIC_SET version 1");

        ByteArrayOutputStream outputData = new ByteArrayOutputStream();
        outputData.write(COMMAND_CLASS_KEY);
        outputData.write(BASIC_SET);

        // Process 'Value'
        outputData.write(value);

        return outputData.toByteArray();
    }

    /**
     * Processes a received frame with the BASIC_SET command.
     * <p>
     * Basic Set
     * <p>
     * The output data {@link Map} has the following properties -:
     *
     * <ul>
     * <li>VALUE {@link Integer}
     * </ul>
     *
     * @param payload the {@link byte[]} payload data to process
     * @return a {@link Map} of processed response data
     */
    public static Map<String, Object> handleBasicSet(byte[] payload) {
        // Create our response map
        Map<String, Object> response = new HashMap<String, Object>();

        // Process 'Value'
        response.put("VALUE", Integer.valueOf(payload[2]));

        // Return the map of processed response data;
        return response;
    }

    /**
     * Creates a new message with the BASIC_GET command.
     * <p>
     * Basic Get
     *
     * @return the {@link byte[]} array with the command to send
     */
    static public byte[] getBasicGet() {
        logger.debug("Creating command message BASIC_GET version 1");

        ByteArrayOutputStream outputData = new ByteArrayOutputStream();
        outputData.write(COMMAND_CLASS_KEY);
        outputData.write(BASIC_GET);

        return outputData.toByteArray();
    }

    /**
     * Processes a received frame with the BASIC_GET command.
     * <p>
     * Basic Get
     *
     * @param payload the {@link byte[]} payload data to process
     * @return a {@link Map} of processed response data
     */
    public static Map<String, Object> handleBasicGet(byte[] payload) {
        // Create our response map
        Map<String, Object> response = new HashMap<String, Object>();

        // Return the map of processed response data;
        return response;
    }

    /**
     * Creates a new message with the BASIC_REPORT command.
     * <p>
     * Basic Report
     *
     * @param value {@link Integer}
     * @return the {@link byte[]} array with the command to send
     */
    static public byte[] getBasicReport(Integer value) {
        logger.debug("Creating command message BASIC_REPORT version 1");

        ByteArrayOutputStream outputData = new ByteArrayOutputStream();
        outputData.write(COMMAND_CLASS_KEY);
        outputData.write(BASIC_REPORT);

        // Process 'Value'
        outputData.write(value);

        return outputData.toByteArray();
    }

    /**
     * Processes a received frame with the BASIC_REPORT command.
     * <p>
     * Basic Report
     * <p>
     * The output data {@link Map} has the following properties -:
     *
     * <ul>
     * <li>VALUE {@link Integer}
     * </ul>
     *
     * @param payload the {@link byte[]} payload data to process
     * @return a {@link Map} of processed response data
     */
    public static Map<String, Object> handleBasicReport(byte[] payload) {
        // Create our response map
        Map<String, Object> response = new HashMap<String, Object>();

        // Process 'Value'
        response.put("VALUE", Integer.valueOf(payload[2]));

        // Return the map of processed response data;
        return response;
    }
}
